In [1]:
import pandas as pd
import os
import sys
import re
import numpy as np

In [2]:
sample_regex = re.compile(r"GSM[0-9]{7}")

def get_sample_id(filename):
    return sample_regex.search(filename).group()

In [21]:
df = pd.read_csv("data/GSM3478792_P5_matrix.csv")
df.head()

,Index,AAACCTGAGCCACCTG-1,AAACCTGAGTTTCCTT-1,AAACCTGCAAACAACA-1,AAACCTGCAAGAGGCT-1,AAACCTGCAAGGTTTC-1,AAACCTGGTCGTGGCT-1,AAACCTGGTGCTTCTC-1,AAACCTGGTGTGACGA-1,AAACCTGTCCGTTGTC-1,...,TTTGGTTTCCTAAGTG-1,TTTGGTTTCTACCAGA-1,TTTGTCAAGAAACCAT-1,TTTGTCAAGAACTGTA-1,TTTGTCAAGGCTAGGT-1,TTTGTCAAGGCTCTTA-1,TTTGTCACAAGCCGTC-1,TTTGTCACAGCGTTCG-1,TTTGTCACAGGATCGA-1,TTTGTCATCTGCGACG-1
0,ENSG00000243485,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,ENSG00000237613,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,ENSG00000186092,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,ENSG00000238009,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,ENSG00000239945,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
sample_id = get_sample_id("data/GSM3478792_P5_matrix.csv")
sample_id

'GSM3478792'

In [23]:
df.shape

(33694, 4487)

In [22]:
number_of_cells = df.shape[1] - 1 # -1 za Index(gene) kolonu

In [34]:
df.columns = [df.columns[0]] + [sample_id + "_" + str(cell_number) for cell_number in range(1, number_of_cells+1)]
df.head()

,Index,GSM3478792_1,GSM3478792_2,GSM3478792_3,GSM3478792_4,GSM3478792_5,GSM3478792_6,GSM3478792_7,GSM3478792_8,GSM3478792_9,...,GSM3478792_4477,GSM3478792_4478,GSM3478792_4479,GSM3478792_4480,GSM3478792_4481,GSM3478792_4482,GSM3478792_4483,GSM3478792_4484,GSM3478792_4485,GSM3478792_4486
0,ENSG00000243485,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,ENSG00000237613,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,ENSG00000186092,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,ENSG00000238009,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,ENSG00000239945,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [39]:
df = df.set_index("Index")
df = df.transpose()
df.head()

Index,ENSG00000243485,ENSG00000237613,ENSG00000186092,ENSG00000238009,ENSG00000239945,ENSG00000239906,ENSG00000241599,ENSG00000279928,ENSG00000279457,ENSG00000228463,...,ENSG00000277196,ENSG00000277630,ENSG00000278384,ENSG00000278633,ENSG00000276345,ENSG00000277856,ENSG00000275063,ENSG00000271254,ENSG00000277475,ENSG00000268674
GSM3478792_1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
GSM3478792_2,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
GSM3478792_3,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
GSM3478792_4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
GSM3478792_5,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [41]:
df.shape

(4486, 33694)

In [1]:
df.reset_index()

NameError: name 'df' is not defined